### ISSUE TITLE
PackedNode type need modifications.

### ISSUE THREAD

**Issue by NamsooCho** [tox-rs/tox#135]
Current PackedNode is

<pre><code>
 pub struct PackedNode {
     /// Socket addr of node.
     pub saddr: SocketAddr,
     /// Public Key of the node.
     pub pk: PublicKey,
}
</code></pre>

But , I suggest it to 

<pre><code>
pub struct PackedNode {
        /// Socket addr of node.
    pub saddr: SocketAddr,
        /// Public Key of the node.
    pub pk: PublicKey,
        /// Status of node
    pub status: NodeStatus,
        // last responded time
    pub last_resp_time: Instant,
}
</code></pre>
Here, NodeStatus
<pre><code>
pub enum NodeStatus {
    /// online
    Good,
    /// maybe offline
    Bad,
}
</code></pre>

Because of absence of concept of timeout in current implementation,
We can not replace BAD node with GOOD node.

BAD node means that a node do not  receive a response packet for over 162 seconds.
So, it may be a offline node.
To replace BAD node with GOOD node,
distance() in kbucket.rs can be changed.

Current implementation is
<pre><code>
impl Distance for PublicKey {
    fn distance(&self,
                &PublicKey(ref pk1): &PublicKey,
                &PublicKey(ref pk2): &PublicKey) -> Ordering {

        trace!(target: "Distance", "Comparing distance between PKs.");
        let &PublicKey(own) = self;
        for i in 0..PUBLICKEYBYTES {
            if pk1[i] != pk2[i] {
                return Ord::cmp(&(own[i] ^ pk1[i]), &(own[i] ^ pk2[i]))
            }
        }
        Ordering::Equal
    }
}
</code></pre>

Suggestion is

<pre><code>
impl Distance for PublicKey {
    fn distance(&self,
                node1: &mut PackedNode,
                node2: &mut PackedNode,
                bad_node_timeout: Duration) -> Ordering {

        trace!(target: "Distance", "Comparing distance between PKs.");
        if node1.last_resp_time.elapsed() > bad_node_timeout {
            node1.status = NodeStatus::Bad;
        }
        if node2.last_resp_time.elapsed() > bad_node_timeout {
            node2.status = NodeStatus::Bad;
        }

        match node1.status {
            NodeStatus::Good => {
                match node2.status {
                    NodeStatus::Good => { // Good, Good
                        let &PublicKey(own) = self;
                        let PublicKey(pk1) = node1.pk;
                        let PublicKey(pk2) = node2.pk;
                        for i in 0..PUBLICKEYBYTES {
                            if pk1[i] != pk2[i] {
                                return Ord::cmp(&(own[i] ^ pk1[i]), &(own[i] ^ pk2[i]))
                            }
                        }
                        Ordering::Equal
                    },
                    NodeStatus::Bad => { // Good, Bad
                        Ordering::Less // Good is closer
                    },
                }
            },
            NodeStatus::Bad => {
                match node2.status {
                    NodeStatus::Good => { // Bad, Good
                        Ordering::Greater // Bad is farther
                    },
                    NodeStatus::Bad => { // Bad, Bad
                        let &PublicKey(own) = self;
                        let PublicKey(pk1) = node1.pk;
                        let PublicKey(pk2) = node2.pk;
                        for i in 0..PUBLICKEYBYTES {
                            if pk1[i] != pk2[i] {
                                return Ord::cmp(&(own[i] ^ pk1[i]), &(own[i] ^ pk2[i]))
                            }
                        }
                        Ordering::Equal
                    },
                }
            },
        }
    }
}
</code></pre>

**Comment by kpp** [comment]
I don't like the distance to depend on the status of the node

**Comment by kurnevsky** [comment]
> Node having possibility of offline should be replaced with higher priority.
But we can compare nodes outside of `distance` function, just check status if `distance` returns `Equal`. `distance` is used not only for DHT and shouldn't be dependent on node status.

**Comment by kpp** [comment]
`DhtNode` is a good suggestion

**Comment by NamsooCho** [comment]
Then I will create DhtNode type, and replace_order() function.
replace_order() will compare status of node and PK's distance.
replace_order() will be used in Kbucket and Bucket.
So, Bucket struct will changed from

<pre><code>
struct Bucket {
    nodes: Vec&lt;PackedNode&gt;
    ...
}
</code></pre>
to

<pre><code>
struct Bucket {
    nodes: Vec&lt;DhtNode&gt;
    ....
}
</code></pre>

**Comment by kpp** [comment]
let's try

**Comment by kurnevsky** [comment]
Then we can merge `ClientData` with `DhtNode`.
