### ISSUE TITLE
Errors during dht server's start-up

### ISSUE THREAD

**Issue by NamsooCho** [tox-rs/tox#141]
Dht server runs for long time.
I got log messages below.
After some times have passed, there is no error.

NamSooui-MacBook-Pro:examples joe$ RUST_LOG=error cargo run --example dht_node
   Compiling tox v0.0.4 (file:///Users/joe/work/tox)
    Finished dev [unoptimized + debuginfo] target(s) in 5.36 secs
     Running `/Users/joe/work/tox/target/debug/examples/dht_node`
ERROR 2018-05-19T03:55:06Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionRequest2::get_payload() failed: Custom { kind: Other, error: StringError(\"OnionRequest2 decrypt error.\") }") }
ERROR 2018-05-19T03:55:06Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionRequest2::get_payload() failed: Custom { kind: Other, error: StringError(\"OnionRequest2 decrypt error.\") }") }
ERROR 2018-05-19T03:55:08Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("NodesRequest::get_payload() failed: Custom { kind: Other, error: StringError(\"NodesRequest decrypt error.\") }") }
ERROR 2018-05-19T03:55:10Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
ERROR 2018-05-19T03:55:10Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
ERROR 2018-05-19T03:55:11Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
ERROR 2018-05-19T03:55:13Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
lan_wakeup
ERROR 2018-05-19T03:55:24Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
lan_wakeup
ERROR 2018-05-19T03:55:28Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
ERROR 2018-05-19T03:55:30Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
ERROR 2018-05-19T03:55:31Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
lan_wakeup
ERROR 2018-05-19T03:55:39Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
lan_wakeup
ERROR 2018-05-19T03:55:48Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("NodesRequest::get_payload() failed: Custom { kind: Other, error: StringError(\"NodesRequest decrypt error.\") }") }
ERROR 2018-05-19T03:55:48Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("NodesRequest::get_payload() failed: Custom { kind: Other, error: StringError(\"NodesRequest decrypt error.\") }") }
ERROR 2018-05-19T03:55:52Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("NodesRequest::get_payload() failed: Custom { kind: Other, error: StringError(\"NodesRequest decrypt error.\") }") }
lan_wakeup
ERROR 2018-05-19T03:56:00Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
ERROR 2018-05-19T03:56:02Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("NodesRequest::get_payload() failed: Custom { kind: Other, error: StringError(\"NodesRequest decrypt error.\") }") }
ping_wakeup
lan_wakeup
ERROR 2018-05-19T03:56:08Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("NodesRequest::get_payload() failed: Custom { kind: Other, error: StringError(\"NodesRequest decrypt error.\") }") }
ERROR 2018-05-19T03:56:09Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("NodesRequest::get_payload() failed: Custom { kind: Other, error: StringError(\"NodesRequest decrypt error.\") }") }
ERROR 2018-05-19T03:56:09Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
ERROR 2018-05-19T03:56:10Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
lan_wakeup
ERROR 2018-05-19T03:56:17Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
lan_wakeup
ERROR 2018-05-19T03:56:32Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
lan_wakeup
lan_wakeup
ERROR 2018-05-19T03:56:48Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("NodesRequest::get_payload() failed: Custom { kind: Other, error: StringError(\"NodesRequest decrypt error.\") }") }
ERROR 2018-05-19T03:56:48Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
ERROR 2018-05-19T03:56:52Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("NodesRequest::get_payload() failed: Custom { kind: Other, error: StringError(\"NodesRequest decrypt error.\") }") }
lan_wakeup
ERROR 2018-05-19T03:57:02Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("NodesRequest::get_payload() failed: Custom { kind: Other, error: StringError(\"NodesRequest decrypt error.\") }") }
ping_wakeup
lan_wakeup
ERROR 2018-05-19T03:57:08Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("NodesRequest::get_payload() failed: Custom { kind: Other, error: StringError(\"NodesRequest decrypt error.\") }") }
lan_wakeup
ERROR 2018-05-19T03:57:21Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("OnionAnnounceRequest decrypt error.") }
lan_wakeup
lan_wakeup
lan_wakeup
ERROR 2018-05-19T03:57:48Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("NodesRequest::get_payload() failed: Custom { kind: Other, error: StringError(\"NodesRequest decrypt error.\") }") }
ERROR 2018-05-19T03:57:52Z: dht_node: failed to handle packet: Custom { kind: Other, error: StringError("NodesRequest::get_payload() failed: Custom { kind: Other, error: StringError(\"NodesRequest decrypt error.\") }") }
lan_wakeup
ping_wakeup
lan_wakeup
lan_wakeup
lan_wakeup
lan_wakeup
lan_wakeup
lan_wakeup
ping_wakeup
lan_wakeup
lan_wakeup
lan_wakeup
lan_wakeup
lan_wakeup
lan_wakeup
ping_wakeup
lan_wakeup
lan_wakeup
lan_wakeup
lan_wakeup
lan_wakeup

**Comment by kurnevsky** [comment]
Did you restart tox node before you got these errors? If so then it's normal because nodes you were connected to don't know that your DHT key is changed and send packets with old key. Your restarted node can't decrypt them and you get such errors in the log.
Btw, for `OnionRequest`'s it's ok to see these errors even you don't restart nodes - onion key is changed every 2 hours.

**Comment by NamsooCho** [comment]
Right.
With --const-key, error disappears.
BTW, ping_id mismatch error is not found.
