### ISSUE TITLE
Use lazy_static

### ISSUE THREAD

**Issue by NamsooCho** [tox-rs/tox#149]
Functions of DHT have many timeouts and intervals.
These values are passed as parameters from main() function.

I am considering lazy_static crate.

The code will be something like this.

<pre><code>
lazy_static! {
    /// timeout for remove clients in peers_cache
    pub static ref KILL_NODE_TIMEOUT: Mutex<Duration> = Mutex::new(Duration::from_secs(0));
    /// timeout for PingRequest and NodesRequest
    pub static ref PING_TIMEOUT: Mutex<Duration> = Mutex::new(Duration::from_secs(0));
    /// interval for ping
    pub static ref PING_INTERVAL: Mutex<Duration> = Mutex::new(Duration::from_secs(0));
    /// timeout for node is offline or not
    pub static ref BAD_NODE_TIMEOUT: Mutex<Duration> = Mutex::new(Duration::from_secs(0));
    /// interval for random NodesRequest
    pub static ref NODES_REQ_INTERVAL: Mutex<Duration> = Mutex::new(Duration::from_secs(0));
    /// interval or NatPingRequest
    pub static ref NAT_PING_REQ_INTERVAL: Mutex<Duration> = Mutex::new(Duration::from_secs(0));
}

/// set static variables
pub fn set_config_values(args: ConfigArgs) {
    *KILL_NODE_TIMEOUT.lock().unwrap() = Duration::from_secs(args.kill_node_timeout);
    *PING_TIMEOUT.lock().unwrap() = Duration::from_secs(args.ping_timeout);
    *PING_INTERVAL.lock().unwrap() = Duration::from_secs(args.ping_interval);
    *BAD_NODE_TIMEOUT.lock().unwrap() = Duration::from_secs(args.bad_node_timeout);
    *NODES_REQ_INTERVAL.lock().unwrap() = Duration::from_secs(args.nodes_req_interval);
    *NAT_PING_REQ_INTERVAL.lock().unwrap() = Duration::from_secs(args.nat_ping_req_interval);
}
</code></pre>

Using lazy_static has some benefits.

- no need to pass parameters
- can change value for test functions

But, there is serious problem.

- can't run test functions concurrently, because test functions are threads and lazy_static STATIC variables are shared.

Which choice will be better?

**Comment by kurnevsky** [comment]
I'd prefer to use `const`s. In this case we can change time type from `Instant` to `SystemTime` and in tests set this time manually to the past. It's simpler than this magic with lazy static. And one more benefit - `SystemTime` is more precise than `Instant`:

> Note, however, that instants are not guaranteed to be steady. In other words, each tick of the underlying clock may not be the same length (e.g. some seconds may be longer than others). An instant may jump forwards or experience time dilation (slow down or speed up), but it will never go backwards.

**Comment by kurnevsky** [comment]
One thing that came to my mind - we can define different constants for tests and real code, using `cfg` attribute:
```rust
#[cfg(not(test))]
const MY_CONST: u32 = 1;
#[cfg(test)]
const MY_CONST: u32 = 123;
```

**Comment by kurnevsky** [comment]
As @kpp proposed we can use new [clock api](https://tokio-rs.github.io/tokio/tokio_timer/clock/index.html) from tokio-timer. It allows to mock `Instant:time` using [custom context](https://github.com/tokio-rs/tokio/blob/master/tokio-timer/tests/clock.rs#L38-L51) in tests. It seems it will be enough for our case.

**Comment by kurnevsky** [comment]
https://github.com/tox-rs/tox/pull/154

**Comment by kpp** [comment]
Do we need this issue anymore?

**Comment by kurnevsky** [comment]
It depends. We still have these values as variables in config, and it's better to refactor it and change them to consts.
