### ISSUE TITLE
Need to fork the reference documentation again

### ISSUE THREAD

**Issue by hugbubby** [tox-rs/tox#153]
Downstream has heavily modified the reference specification since zetok ghosted. I'd like to incorporate some of these changes but I don't think he'll respond to the pull requests. Can we get a clone of the reference specification as a repository under tox-rs?

**Comment by kpp** [comment]
Sure. Will you fill it from scratch? How do I name the repo?

**Comment by kpp** [comment]
Are you talking about https://github.com/zetok/tox-spec ?

**Comment by hugbubby** [comment]
Yes, my plan is to update it from scratch. Probably a good idea to name it "spec" or "tox-spec", depending on whether or not you think tox-rs makes the "tox" redundant.

**Comment by kpp** [comment]
Here you are: https://github.com/tox-rs/tox-spec

**Comment by kpp** [comment]
@hugbubby hello?
