### ISSUE TITLE
future plans (full feature persistent chats, without bots)

### ISSUE THREAD

**Issue by who-am-1** [tox-rs/tox#213]
Just a question.

in mainline toxcore, at least 2-3 PRs with persistent chats were rejected or abandoned

work on persistent chats has been going on for many years by different developers and all they could do is https://github.com/TokTok/c-toxcore/pull/1069#pullrequestreview-152513775
It's minimal persistence (across disconnect, not across client restart). Still will not work without the group bot.

do you have plans to go further c-toxcore and implement full feature persistent chats, change reference implementation docs and leave c-toxcore in the past (marked as deprecated)?

**Comment by kpp** [comment]
Sure.
