### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by mazocomp** [tox-rs/tox#236]
You state that everyone is free to use this code under the terms of either MIT or GPLv3, but that means GPLv3 doesn't have any power here at all, so what's the point of GPLv3 being here?

**Comment by kpp** [comment]
See https://github.com/tox-rs/tox/pull/162#issuecomment-407807173

**Comment by kpp** [comment]
I am closing this issue since there is no response from the author.

**Comment by mazocomp** [comment]
@kpp I think I got the difference between dual license and multi license.
