### ISSUE TITLE
Proposal to improve errors definitions

### ISSUE THREAD

**Issue by kurnevsky** [tox-rs/tox#354]
# Motivation

Currently we have to write a lot of boilerplate code to define custom errors. It includes `Error` and `ErrorKind` definitions, `Into` trait implementation and tests. This proposal demonstrates some changes that can help us to reduce necessary code for errors definitions.

# Detailed design

## `Into` trait

To build one error from another we define `Into` trait. This means that error kind is always logically bounded to some error type it is constructed from. In turns this leads us to very generic error kinds and inability to distinguish different errors with same type. Let's consider `GetPayloadError` as an example. We always convert it to the same `GetPayload` variant which means the only way to see what packet was invalid is to check out backtrace. Another example - `std::io::Error` which can happen in various cases but we bound it to `SendTo` variant.

Instead of using `Into` trait we can build errors in place:

```rust
SomeError::from(e)
```

turns into

```rust
e.context(ErrorKind::Variant).into()
```

`into` here converts `Context<ErrorKind>` to `Error` and can be omitted under some circumstances (`?` operator, including `async` functions).

## `error_kind` macros

To reduce Error and ErrorKind definitions we can define a macros:

```rust
macro_rules! error_kind {
    ($(#[$error_attr:meta])* $error:ident, $(#[$kind_attr:meta])* $kind:ident { $($variants:tt)* }) => {
        #[derive(Debug)]
        $(#[$error_attr])*
        pub struct $error {
            ctx: Context<$kind>,
        }

        impl $error {
            /// Return the kind of this error.
            pub fn kind(&self) -> &$kind {
                self.ctx.get_context()
            }
        }

        impl Fail for $error {
            fn cause(&self) -> Option<&Fail> {
                self.ctx.cause()
            }

            fn backtrace(&self) -> Option<&Backtrace> {
                self.ctx.backtrace()
            }
        }

        impl fmt::Display for $error {
            fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
                self.ctx.fmt(f)
            }
        }

        #[derive(Clone, Debug, Eq, PartialEq, Fail)]
        $(#[$kind_attr])*
        pub enum $kind {
            $($variants)*
        }

        impl From<$kind> for $error {
            fn from(kind: $kind) -> $error {
                $error::from(Context::new(kind))
            }
        }

        impl From<Context<$kind>> for $error {
            fn from(ctx: Context<$kind>) -> $error {
                $error { ctx }
            }
        }
    }
}
```

Then we can define errors with:

```rust
error_kind! {
    #[doc = "Some doc"]
    SomeError,
    #[doc = "Some doc"]
    SomeErrorKind {
        #[doc = "Some doc"]
        #[fail(display = "Some description")]
        Variant1,
        #[doc = "Some doc"]
        #[fail(display = "Some description")]
        Variant2,
    }
}
```

## Tests

To reason `kcov` we have to write a lot of test that are not really check something useful. This includes Display and From traits, cause and backtrace methods.

With macros defined in previous section we can write tests only once:

```rust
#[cfg(test)]
mod tests {
    use super::*;

    error_kind! {
        TestError,
        TestErrorKind {
            #[fail(display = "Variant1")]
            Variant1,
            #[fail(display = "Variant2")]
            Variant2,
        }
    }

    #[test]
    fn test_error() {
        assert_eq!(format!("{}", TestErrorKind::Variant1), "Variant1".to_owned());
        assert_eq!(format!("{}", TestErrorKind::Variant2), "Variant2".to_owned());
    }

    #[test]
    fn test_error_variant_1() {
        let error = TestError::from(TestErrorKind::Variant1);
        assert!(error.cause().is_none());
        assert!(error.backtrace().is_some());
        assert_eq!(format!("{}", error), "Variant1".to_owned());
    }

    #[test]
    fn test_error_variant_2() {
        let error = TestError::from(TestErrorKind::Variant2);
        assert!(error.cause().is_none());
        assert!(error.backtrace().is_some());
        assert_eq!(format!("{}", error), "Variant2".to_owned());
    }
}
```

These test will cover all error related code since it's defined by a macro.

# Notes

- We should avoid building errors from other statically known errors, e.g. `OneError::from(OneErrorKind::Variant1).context(AnotherErrorKind::Variant2).into()`. Instead, we should add `Variant1` to `AnotherErrorKind`.

# Alternatives

- Use alternative patterns as described in [this section](https://github.com/rust-lang-nursery/failure/blob/master/book/src/error-errorkind.md#when-might-you-use-this-pattern).
- Drop `failure` dependency and implement all error enums ouselves.

# Drawbacks

- We will have to use `doc` attribute instead of `///`.

**Comment by kurnevsky** [comment]
Check out my `errors` branch for the example: https://github.com/tox-rs/tox/tree/errors

**Comment by NamsooCho** [comment]
If the `Variant` has attached data, how to carry it?
For example, A nom error `Incomplete(Needed)`, want to display not only `error` but also `Needed`.

**Comment by kpp** [comment]
> If the Variant has attached data, how to carry it?

@kurnevsky this is quite interesting

**Comment by kurnevsky** [comment]
The same as before - macros takes tt* so you can put inside anything you want.

**Comment by kpp** [comment]
Can you give me an example?

**Comment by kurnevsky** [comment]
https://github.com/tox-rs/tox/pull/357/commits/611f506e0050631ed819a1946d7044d556489874

**Comment by kpp** [comment]
Good

**Comment by kurnevsky** [comment]
Implemented via https://github.com/tox-rs/tox/pull/357
