### ISSUE TITLE
iOS &/or Android

### ISSUE THREAD

**Issue by NeoChow** [tox-rs/tox#377]
Could it or the client side run on iOS or Android ?

**Comment by kpp** [comment]
We test it on MacOS. I believe you can run it on iOS or Android however we don't have build scripts for xcompilation to iOS or Android.
Are you interested in it?

**Comment by NeoChow** [comment]
Actually I did not have much experience in writing build scripts, but I'll give it a try when there's time. : )

**Comment by kpp** [comment]
You can combine both https://github.com/sodiumoxide/sodiumoxide/#cross-compiling-for-armv7-unknown-linux-musleabihf-via-docker and https://medium.com/visly/rust-on-android-19f34a2fb43

**Comment by NeoChow** [comment]
thanks very much : )

**Comment by kpp** [comment]
Please share your UX and build scripts if you can crosscompile our project.
