### ISSUE TITLE
examples/echo.rs: remove hardcoded keys

### ISSUE THREAD

**Issue by kpp** [tox-rs/tox#379]
Generate an id each time and take friend's TOX_ID from cli args

**Comment by kurnevsky** [comment]
Currently there is no easy way to make friends so we can't use echo server without specially prepared profile. So it doesn't make much sense to take friends from cli args. Instead we should handle friend requests and just accept any received request.

**Comment by kpp** [comment]
> without specially prepared profile

Why? The algo to run echo.rs should be the following:
1) run echo.rs with FRIEND_TOX_ID
2) take SELF_TOX_ID
3) open a tox client
4) send friend request to SELF_TOX_ID

**Comment by kurnevsky** [comment]
> 4. send friend request to SELF_TOX_ID

How can it be sent? Currently we can't send or accept friend requests with echo.rs.

**Comment by kpp** [comment]
Then we should accept friend requests =)

**Comment by inosms** [comment]
Ok I think I'll take this one :)

**Comment by kpp** [comment]
I think this is not a good first issue, because it will be hard to accept friend requests. But you may try.

**Comment by inosms** [comment]
Probably my understanding of `echo.rs` is wrong but, isn't accepting already implemented via the `friend_connections.add_friend(friend_pk);` call? or do I have do "reaccept" when I receive a Friend Request Package (`0x12`)? For me it seems to work locally.

**Comment by kpp** [comment]
Would you please create a PR? I will take a look

**Comment by inosms** [comment]
ok if it's all then I need a bit more time
