### ISSUE TITLE
Race in toxcore::tcp::client::client::tests::spawn

### ISSUE THREAD

**Issue by kurnevsky** [tox-rs/tox#381]
https://ci.appveyor.com/project/tox-rs/tox/builds/24915443/job/3h7elerbm9lw1huj

It seems it can happen when a client sent message before the server started.

**Comment by kpp** [comment]
Maybe. Did we have issues with almost similar code https://github.com/tox-rs/tox/blob/master/src/toxcore/tcp/handshake/mod.rs#L323 ?

**Comment by kurnevsky** [comment]
Not that I remember of. But I don't see other reasons why the `spawn` test might have hung. And if I remove the server from this test it hangs exactly like on appveyor.

**Comment by kpp** [comment]
How about increasing the number of connection attempts? Also we can set up timeout to kill a client future and fail tests instead of hanging forever.
