### ISSUE TITLE
Replace Digest with a plain array in OnionAnnounceResponsePayload

### ISSUE THREAD

**Issue by kurnevsky** [tox-rs/tox#387]
[OnionAnnounceResponsePayload.ping_id_or_pk](https://github.com/tox-rs/tox/blob/a971a93ba33c09accf2ad1a06a023e684d0b49b1/src/toxcore/onion/packet/onion_announce_response.rs#L135) can contain either `sha256::Digest` or `PublicKey`. Currently we store it as `sha256::Digest` and convert to `PublicKey` when needed. Instead it'd be better to store it as plain array `[u8; 32]` to not misuse `sha256::Digest`.

**Comment by Atul9** [comment]
@kurnevsky I am new to Rust and this project.
I tried to make the change locally and ran tests. I think the size of the array should be 91 since in `onion_announce.rs` ping_id function makes use of `ONION_PING_DATA_SIZE` which is 91. I came across this while fixing the failing tests.

**Comment by kurnevsky** [comment]
1. No, it should be 32 bytes - the length of curve25519 key and sha256 hash. `ONION_PING_DATA_SIZE` is the size of a data from which we calculate sha256 hash.
2. We treat `ping_id_or_pk` as a key or as a hash depending on `AnnounceStatus` from a packet. So we just need to construct key and hash in the right places.
3. Yes, `ping_id_or_pk` is still either a hash or a key. We just want to store it as a plain array unless we don't know what it is.
4. It's either a hash or a key.
