### ISSUE TITLE
Failure is deprecated

### ISSUE THREAD

**Issue by suhr** [tox-rs/tox#424]
> Notice: failure is deprecated. If you liked failure's API, consider using:
> - Anyhow is a good replacement for `failure::Error`.
> - thiserror is a good, near drop-in replacement for `#[derive(Fail)]`.

**Comment by kpp** [comment]
=(

**Comment by kpp** [comment]
Haw about https://github.com/yaahc/displaydoc ?

**Comment by suhr** [comment]
Using a doc comments as a source feels a bit hacky to me.
