### ISSUE TITLE
Question: tox-rs vs. c-toxcore - differences when deployed as server node

### ISSUE THREAD

**Issue by kotelnik** [tox-rs/tox#462]
Hi! First, thanks for working on tox!

Right now I'm running one of the public tox nodes using c-toxcore. My question is whether this project is a parallel one with c-toxcore and basically on par with implemented server features, or is this one a successor? Should I run it instead? :)

Thanks!

**Comment by kpp** [comment]
Hi! There are tox-rs nodes on https://nodes.tox.chat/ by Stranger and kurnevsky. So the implementation is binary compatible.

**Comment by kotelnik** [comment]
I even noticed that but I wasn't sure if all c-toxcore features (like audio/video calls, file transfer) are supported. I understand now it probably is supported or it is client-part feature only. As you can see I'm not a tox protocol expert by far, sorry about that :-)

Anyway, thanks for you fast and assuring answer! :)

**Comment by kpp** [comment]
That's right, these are client-part features only.

Feel free to ask anything (or close the issue).

**Comment by kotelnik** [comment]
All is now crystal clear, thanks again! :) Closing.
