### ISSUE TITLE
encrypt & decrypt between PC

### ISSUE THREAD

**Issue by NamsooCho** [tox-rs/tox#57]
I am testing dht_node_new.rs

First, I try peer to peer (Linux VM to MacOS) communication sending PingRequest to each other.
There is get_payload() decrypt error.

Then, I try to loopback on MacOS sending PingRequest.
There is not get_payload() decrypt error.

The version of libsodium of Mac and Linux is different.

**Comment by NamsooCho** [comment]
I make two Linux VMs.
Send PingRequest to other VM.
When receiving PingRequest, the get_payload() decrypt error occurs.

**Comment by kpp** [comment]
Closed due to fixes in https://github.com/tox-rs/tox/pull/59
