### ISSUE TITLE
Lan Discovery Human doc.

### ISSUE THREAD

**Issue by NamsooCho** [tox-rs/tox#74]
### Description for lan discovery ###

Every 10 seconds, node sends Lan Discovery packet to it's interfaces broadcast addresses, global broadcast address(255.255.255.255), Ipv6 broadcast address(FF02::1).

When interval timer expires send_lan_discovery() is called.

send_lan_discovery()

    - call get_broadcast_addresses()
        - call get_ipv4_broadcast_addrs()
        it uses crate named "get_if_addrs" to get ipv4 broadcast addresses.
    after get interfaces ipv4 broadcast addresses, it plus ipv4 global broadcase address(255.255.255.255), ipv6 global broadcast address(FF02::1).

    - create LanDiscovery packet

    - send packet to boradcast addresses

When node received LanDiscovery packet, it creates NodesRequest packet and send back to sender of LanDiscovery packet.

In NodesRequest packet, the pk of payload is 'Sender's PK of LanDiscovery.

When the node sent LanDiscovery receives NodesRequest packet, it responds with NodesResponse packet. It results in a lan bootstrapping.

**Comment by kpp** [comment]
Closed due to https://github.com/tox-rs/tox/pull/78
